[mgr]
show_hidden = true

[opener]
play = [
        { run = 'mpv %s', orphan = true }
]
edit = [
        { run = 'kitty nvim %s', orphan = true }
]

[open]
rules = [
        { mime = "text/*", use = "edit" },
        { mime = "video/*", use = "play" },
]
